Display friend list
WildCodeSchool/toulouse-0919-js-p2-steam_finder pull request #22
Opened 2019-11-13 10:57 UTC by Borreill

Affichage liste d'amis
Barre de recherche
+ Bonus

2019-11-13 16:14 UTC, Ticka971 approved these changes
ok

2019-11-14 07:07 UTC, Froyj requested changes
Quand j'essaie de tester l'appli, la barre de recherche s'affiche mal. J'ai l'impression qu'il manque des choses par rapport à dev.
Assurer vous d'avoir merge dev dans DisplayFriendList de manière à avoir une version pleinement fonctionnelle.
Pour vérifier si tout est ok, regarder dans la pull request le merge peut se faire sans conflit (ca s'affichera tout en vert, sinon en noir)

2019-11-14 08:20 UTC, Borreill commented
Normalement c'est bon

2019-11-14 09:48 UTC, Froyj approved these changes

2019-11-14 10:09 UTC, merged